from random import *
import turtle
turtle.colormode(255)
turtle.Screen().bgcolor(135,206,250)
# tom = racer(-200, 200, "red")
tom = turtle.Turtle()
tom.penup()
tom.goto(-200, 200)
tom.color("red")
tom.shape("turtle")

# tommy = racer(-200, 170, "orange")
tommy = turtle.Turtle()
tommy.penup()
tommy.goto(-200, 170)
tommy.color("orange")
tommy.shape("turtle")
# bob = racer(-200, 140, "yellow")
bob = turtle.Turtle()
bob.penup()
bob.goto(-200, 140)
bob.color("yellow")
bob.shape("turtle")
# bobby = racer(-200, 110, "green")
bobby = turtle.Turtle()
bobby.penup()
bobby.goto(-200, 110)
bobby.color("green")
bobby.shape("turtle")
# jim = racer(-200, 80, "blue")
jim = turtle.Turtle()
jim.penup()
jim.goto(-200, 80)
jim.color("blue")
jim.shape("turtle")
# jimmy = racer(-200, 50, "purple")
jimmy = turtle.Turtle()
jimmy.penup()
jimmy.goto(-200, 50)
jimmy.color("purple")
jimmy.shape("turtle")

tom.right(360)
tommy.right(360)
bob.right(360)
bobby.right(360)
jim.right(360)
jimmy.right(360)

pen = turtle.Turtle()
pen.hideturtle()
pen.penup()
pen.goto(-180, 210)
pen.pendown()
pen.right(90)
pen.forward(200)
pen.penup()
pen.goto(30, 210)
pen.pendown()
pen.forward(200)
pen.penup()
pen.goto(-210, 220)
pen.pendown()
pen.write("START")
pen.penup()
pen.goto(10, 220)
pen.pendown()
pen.write("FINSH")
for i in range(75):

    tomSpeed = randint(1, 5)
    tommySpeed = randint(1, 5)
    bobSpeed = randint(1, 5)
    bobbySpeed = randint(1, 5)
    jimSpeed = randint(1, 5)
    jimmySpeed = randint(1, 5)
    tom.forward(tomSpeed)
    tommy.forward(tommySpeed)
    bob.forward(bobSpeed)
    bobby.forward(bobbySpeed)
    jim.forward(jimSpeed)
    jimmy.forward(jimmySpeed)
turtle.done()